### ISSUE TITLE
Frequencies don't stop at end frequency

### ISSUE THREAD

**Issue by ansonl** [dsdanielko/cura-ringing-tower-script#1]
Hi, the script works great for the ringing tower model when the layer height is set to 0.2mm. 

However, when the layer height is set lower and there are more layers, the frequency (for M593) doesn't actually stop at the specified end frequency or nor is it scaled between the start and end frequencies.

**Comment by dsdanielko** [comment]
Yea, the script is meant to be used specifically with the instructions on https://marlinfw.org/docs/gcode/M593.html which says to use 0.2mm layer height for slicing, I guess I could generalise the script if needed though, why are you using smaller layer heights?

**Comment by ansonl** [comment]
It was my mistake the first time slicing at 0.1mm height but now I'm wondering if the end frequency has a purpose if it will not stop at end frequency or scale with the model. 

Also there may be a case in where a ringing tower may have a different layer or total model height due to printer setup.

**Comment by dsdanielko** [comment]
As far as I know, the input shaping tries to compensate for the most common frequencies of vibration in the printer frame. I presume that the marlin team has concluded that most printers work best when compensating between 15hz and 60hz. With the test print, you compensate for different frequencies in this range at different heights of the print. Then you are working out which compensation value results in the best print by working out the height of least ringing.

**Comment by ansonl** [comment]
Yes, I understand that the recommended frequency is 15 to 60hz on the standard ringing tower print, but is there a need for a start and end frequency input when entering different values in them has no effect on the final inserted gcode?

**Comment by dsdanielko** [comment]
The start and end frequencies should definitely have an impact on the final inserted gcode, I just tested it now with random values like 40 starting and 90 ending. I added the option so advanced users can try different frequencies, but I didn't expect people to use different models/layer heights. I suppose I can add them though, it wouldn't be too difficult

**Comment by dsdanielko** [comment]
Ok different layer heights/max height should be supported now, do open another issue if it doesn't work for you or anything else
